name: Main

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Lint golang code
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

      - name: Run tests
        run: make test

      - name: Build binary
        run: make build.binaries

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: go

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
